// This file is generated by Slice Machine. Update with care!

import MarkdownList from './MarkdownList';
import PostCopy from './PostCopy';
import PostImage from './PostImage';
import YoutubeVideo from './YoutubeVideo';

export {
  MarkdownList,
  PostCopy,
  PostImage,
  YoutubeVideo,
};

export const components = {
  markdown_list: MarkdownList,
  post_copy: PostCopy,
  post_image: PostImage,
  youtube_video: YoutubeVideo,
};
