// This file is generated by Slice Machine. Update with care!

import PostCopy from './PostCopy';
import PostImage from './PostImage';

export {
	PostCopy,
	PostImage,
};

export const components = {
	post_copy: PostCopy,
	post_image: PostImage,
};
