// This file is generated by Slice Machine. Update with care!

import PostCopy from './PostCopy';
import PostImage from './PostImage';
import YoutubeVideo from './YoutubeVideo';

export {
  PostCopy,
  PostImage,
  YoutubeVideo,
};

export const components = {
  post_copy: PostCopy,
  post_image: PostImage,
  youtube_video: YoutubeVideo,
};
